# Generated by Selenium 
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By
import time
from bs4 import BeautifulSoup

class Principal():
    def __init__(self, url):
        self.url = url
        try:
            self.driver = webdriver.Remote(command_executor='http://192.168.44.216:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME )
            self.wait = WebDriverWait(self.driver, 10)
        except:
            pass
        print(" 1 - Inicio abrir webdriver y navegador ")
        

    def logica(self):
        self.driver.get(self.url)
        self.driver.maximize_window()
        # container = self.driver.find_element(By.CLASS_NAME , 'paginated-list--infinite')
        noticias = self.driver.find_elements(By.XPATH , '//*[@id="fusion-app"]/div/div[2]/div[35]/div/div[1]/div')
        print("len", len(noticias))
        # i = 0
        # while i < 10:
        #     self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        #     i = i + 1
        #     time.sleep(3)

        for noticia in noticias:
            try:
                noticia.find_element(By.XPATH, './div/div[1]/div[2]/h2').click()
                ventanas = self.driver.window_handles
                print(ventanas)
                html = self.driver.page_source
                soup = BeautifulSoup(html, "html.parser")
                div = soup.find('div')
                h1 = div.find('h1')
                h2 = div.find('h2')
                # tbody = div.find('tbody')
                print("h1", h1)
                print("h2", h2)
               

            except:
                print("except")
                time.sleep(20)
                self.driver.quit()
                pass

     

    def extraData(self, html):
        soup = BeautifulSoup(html, "html.parser")
        div = soup.find('div')
        print("div", div)
        h1 = div.find('h1')
        h2 = div.find('h2')
        # tbody = div.find('tbody')
        print("h1", h1)
        print("h2", h2)
        # titulo = self.driver.find_element(By.XPATH , '/html/body/div[1]/div/div[4]/div[2]/h1').text
        # print("titulo", titulo)
        return 0